version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Show current branch"
          command: "echo ${CIRCLE_BRANCH}"
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:16.19.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: "echo ${CIRCLE_BRANCH}"
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Build project
          command: |
            yarn
            yarn build
            cd dist
            zip ../dist.zip -r * .[^.]*
            echo "Build successfull"
      - run:
          name: Deploy to AWS s3
          command: |
            if ["${CIRCLE_BRANCH}" == "master"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/dist s3://${CINE_PRODUCTION} --delete
            elif ["${CIRCLE_BRANCH}" == "staging"]
            then  
              aws --region ${AWS_REGION} s3 sync ~/repo/dist s3://${CINE_STAGING} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/dist s3://${CINE_DEVELOPMENT} --delete
            fi

  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/node:16.19.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: "echo ${CIRCLE_BRANCH}"
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Build project
          command: |
            yarn
            yarn build
            cd dist
            zip ../dist.zip -r * .[^.]*
            echo "Build successfull"
      - run:
          name: Deploy to AWS Cloudfront
          command: |
            aws configure set preview.cloudfront true
            if ["${CIRCLE_BRANCH}" == "master"]
            then
              aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --path /\*
            elif ["${CIRCLE_BRANCH}" == "staging"]
            then  
              aws cloudfront create-invalidation --distribution-id ${STAG_DISTRIBUTION_ID} --path /\*
            else
              aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --path /\*
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-aws-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - develop
                - staging
                - master
